include .env

run-api:
	PORT=$(PORT) \
	JWT_SECRET=$(JWT_SECRET) \
	OLLAMA_URL=${OLLAMA_URL} \
	OLLAMA_MODEL=$(OLLAMA_MODEL) \
	OLLAMA_SYSTEM_PROMPT=${OLLAMA_SYSTEM_PROMPT} \
	go run ./cmd/api/main.go
